"""
io/transcript.py

Transcript handler for the narrative modality.

Accepts two sources:
    1. Pre-existing CSV in the standardised format (confirmed from Pulp Fiction sample)
    2. Whisper ASR output (generated by transcribe() function below)

Standardised CSV format (confirmed):
    subtitle        str     one word per row, lowercase
    start_time_new  float   word start in seconds from film start
    end_time_new    float   word end in seconds
    interval_new    float   word duration (ignored by pipeline)
    type            str     alignment confidence label

The pipeline uses only: subtitle, start_time_new, end_time_new, type.
Words are optionally filtered by type using config.TRANSCRIPT_TYPES.

IN:  CSV path (or video path for Whisper)
OUT: get_words(second_idx) → space-joined word string for that second
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from cinematic_surprise.config import (
    TRANSCRIPT_COL_WORD,
    TRANSCRIPT_COL_START,
    TRANSCRIPT_COL_END,
    TRANSCRIPT_COL_TYPE,
    TRANSCRIPT_TYPES,
    WHISPER_MODEL,
)

log = logging.getLogger(__name__)


class TranscriptReader:
    """
    Loads a standardised transcript CSV and provides per-second word access.

    Args:
        csv_path         : Path to the transcript CSV
        filter_types     : Word confidence types to include.
                           None means use config.TRANSCRIPT_TYPES.
    """

    def __init__(
        self,
        csv_path:     str | Path,
        filter_types: Optional[List[str]] = None,
    ):
        self.csv_path    = Path(csv_path)
        self.filter_types = filter_types if filter_types is not None else TRANSCRIPT_TYPES

        self._index: Dict[int, str] = {}   # second_idx → word string
        self._load()

    def _load(self) -> None:
        """Load CSV and build a second → words index."""
        df = pd.read_csv(self.csv_path)

        # Validate required columns
        required = [TRANSCRIPT_COL_WORD, TRANSCRIPT_COL_START, TRANSCRIPT_COL_END]
        missing  = [c for c in required if c not in df.columns]
        if missing:
            raise ValueError(
                f"Transcript CSV missing columns: {missing}. "
                f"Expected format: subtitle, start_time_new, end_time_new, "
                f"interval_new, type"
            )

        # Filter by confidence type if type column exists
        if TRANSCRIPT_COL_TYPE in df.columns and self.filter_types:
            df = df[df[TRANSCRIPT_COL_TYPE].isin(self.filter_types)]
            log.info(
                f"Transcript: kept {len(df)} words after filtering to "
                f"types {self.filter_types}"
            )

        # Build second → words lookup
        # A word belongs to a second if its start_time falls within [t, t+1)
        df["_second"] = df[TRANSCRIPT_COL_START].astype(float).apply(int)
        grouped = df.groupby("_second")[TRANSCRIPT_COL_WORD].apply(
            lambda words: " ".join(str(w) for w in words)
        )
        self._index = grouped.to_dict()

        log.info(
            f"Transcript loaded: {len(df)} words, "
            f"{len(self._index)} seconds with speech, "
            f"from '{self.csv_path.name}'"
        )

    def get_words(self, second_idx: int) -> str:
        """
        Return the words spoken during second_idx as a single string.

        Args:
            second_idx : 0-based integer second index

        Returns:
            Space-joined word string, or empty string if no speech.
        """
        return self._index.get(second_idx, "")

    @property
    def seconds_with_speech(self) -> List[int]:
        return sorted(self._index.keys())


def transcribe(
    video_path:  str | Path,
    output:      str | Path,
    model_size:  Optional[str] = None,
) -> Path:
    """
    Phase 1: Run Whisper ASR on a video file and save the transcript CSV.

    The output CSV follows the standardised format accepted by TranscriptReader.
    Run this once per film before the main pipeline.

    Args:
        video_path : Path to the video file
        output     : Path to save the transcript CSV
        model_size : Whisper model size. Defaults to config.WHISPER_MODEL.
                     options: "tiny", "base", "small", "medium", "large"

    Returns:
        Path to the saved CSV.

    Requires:
        pip install openai-whisper
    """
    try:
        import whisper
    except ImportError:
        raise ImportError(
            "openai-whisper is required for transcription. "
            "Install with: pip install openai-whisper"
        )

    size      = model_size or WHISPER_MODEL
    output    = Path(output)
    video_path = Path(video_path)

    log.info(f"Loading Whisper model '{size}'...")
    model = whisper.load_model(size)

    log.info(f"Transcribing '{video_path.name}'...")
    result = model.transcribe(str(video_path), word_timestamps=True)

    # Build DataFrame in standardised format
    rows = []
    for segment in result.get("segments", []):
        for word_info in segment.get("words", []):
            rows.append({
                TRANSCRIPT_COL_WORD:  word_info["word"].strip().lower(),
                TRANSCRIPT_COL_START: word_info["start"],
                TRANSCRIPT_COL_END:   word_info["end"],
                "interval_new":       word_info["end"] - word_info["start"],
                TRANSCRIPT_COL_TYPE:  "matched",   # Whisper words treated as matched
            })

    df = pd.DataFrame(rows)
    df.to_csv(output, index=False)
    log.info(f"Transcript saved: {len(df)} words → '{output}'")
    return output
